//Task1
const name = "Naveen";
console.log(name);

let name1 = "Naveen";
console.log(name1);

var name2 = "Naveen";
console.log(name2);
//Task2
let language = "JavaScript";
console.log(typeof language); 
//Task3
let age = 22;
console.log(typeof age);
//Task4
let isStudent = true;
console.log(typeof isStudent);
//Task5
let salary;
console.log(salary);
//Task6
let fruits = ["Apple", "Banana", "Mango", "Orange", "Grapes"];
console.log(fruits);
//Task7
fruits = ["Apple", "Banana", "Mango", "Orange", "Grapes"];
console.log(fruits[0]);
//Task8
fruits = ["Apple", "Banana", "Mango", "Orange", "Grapes"];
console.log(fruits[2]); 
//Task9
fruits = ["Apple", "Banana", "Mango", "Orange", "Grapes"];
console.log(fruits[fruits.length - 1]);
//Task10
const numbers = [10, 20, 30, 40, 50];
console.log(numbers[1]); 
console.log(numbers[3]);
//Task11
let person = {
  name: "Sai",
  age: 22,
  city: "Narasaraopet"
};
console.log(person);
//Task12
console.log(person.name);
//Task13
person = {
  name: "Naveen",
  age: 25,
  city: "Visakhapatnam",
  skills: ["HTML", "CSS", "JS"] 
};
console.log(person.skills[1]);
//Task14
let carDetails = {
  brand: "Toyota",
  model: "Camry",
  price: 2500000
};
console.log(carDetails.brand); 
//Task15
let fruitCategory = {
  red: ["apple", "cherry"],
  yellow: ["banana", "mango"],
  green: ["kiwi", "grapes"]
};
console.log(fruitCategory.yellow[0]);
//Task16
let a = 8;
let b = 4;
console.log(a + b);
//Task17
console.log(a - b);
//Task18
console.log(a * b);
//Task19
console.log(a / b);
//Task20
console.log(a % b);
//Task21
console.log(3 ** 2);
//Task22
console.log(2 ** 4);
//Task23
let num = 5;
num++; 
console.log(num);
//Task24
let num1 = 10;
num1--;
console.log(num1);
//Task25
let x = 6;
let y = x++;
console.log(x);
console.log(y);
//Task26
let a1 = 4;
let b1 = ++a1;
console.log(a1);
console.log(b1);
//Task27
let value = 10;
value += 5;
console.log(value);
//Task28
let value1 = 20;
value1 -= 3;
console.log(value1);
//Task29
let value2 = 6;
value2 *= 2;
console.log(value2);
//Task30
let value3 = 20;
value3 %= 3;
console.log(value3);
//Task31
console.log(10 == "10");
//Task32
console.log(10 === "10");
//Task33
console.log(15 > 20);
//Task34
console.log(5 <= 10);    
//Task35
console.log(10 > 5 && 5 > 2);
//Task36
console.log(10 < 5 || 8 > 2);
//Task37
console.log(!(5 === "5")); 
//Task38
let age1 = 20;
let result = (age1 >= 18) ? "Adult" : "Minor";
console.log(result);
//Task39
let password = 1;
let status = (password === 1) ? "Login success" : "Wrong password";
console.log(status);
//Task40
let firstName = "Spider";
let lastName = "Man";
console.log(firstName + " " + lastName);
console.log(`${firstName} ${lastName}`); 




